# Generated by Django 6.0.7 on 2026-09-14 10:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doc_type', models.CharField(choices=[('mentions', 'Legal notice'), ('privacy', 'Privacy policy'), ('cgu', 'Terms of use'), ('cgv', 'Terms of sale')], max_length=20, verbose_name='Document')),
                ('language', models.CharField(help_text='Language code, e.g. fr. Same version number across languages.', max_length=10, verbose_name='Language')),
                ('version', models.PositiveIntegerField(default=1, help_text='Shared by every language of the same document version.', verbose_name='Version')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('body_html', models.TextField(blank=True, verbose_name='Body')),
                ('is_current', models.BooleanField(default=False, help_text='Only one version per document and language can be current.', verbose_name='Current version')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Published at')),
                ('requires_acceptance', models.BooleanField(default=True, help_text='Legal notices are informational — untick for those.', verbose_name='Must be accepted')),
                ('requires_reacceptance', models.BooleanField(default=False, help_text='Tick ONLY for a substantive change. Ticked, every user is blocked until they accept again — do not tick for a typo fix.', verbose_name='Force re-acceptance')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Legal document',
                'verbose_name_plural': 'Legal documents',
                'ordering': ['doc_type', 'language', '-version'],
                'indexes': [models.Index(fields=['doc_type', 'language', 'is_current'], name='consent_tra_doc_typ_bfde8c_idx')],
                'constraints': [models.UniqueConstraint(fields=('doc_type', 'language', 'version'), name='uniq_legal_doc_version_per_language')],
            },
        ),
        migrations.CreateModel(
            name='Acceptance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doc_type', models.CharField(choices=[('mentions', 'Legal notice'), ('privacy', 'Privacy policy'), ('cgu', 'Terms of use'), ('cgv', 'Terms of sale')], max_length=20)),
                ('version', models.PositiveIntegerField()),
                ('language_shown', models.CharField(blank=True, help_text='Language actually displayed when consent was given.', max_length=10)),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_acceptances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Legal acceptance',
                'verbose_name_plural': 'Legal acceptances',
                'ordering': ['-accepted_at'],
                'indexes': [models.Index(fields=['user', 'doc_type'], name='consent_tra_user_id_25ae6f_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'doc_type', 'version'), name='uniq_legal_acceptance_per_version')],
            },
        ),
    ]
